apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: javawebappdeployment
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        name: javawebapp
  spec:
    containers:
    - image: lokeshhs591/java-web-app:1
      name: javawebapp
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebappservice
spec:
  selector:
    name: javawebapp
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080